services:
  aggregator:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - data:/app/data
    container_name: aggregator_service

  publisher:
    build:
      context: ./publisher  # Tentukan context secara eksplisit
    # Hapus path 'scripts/' dari command
    command: ["python", "-u", "publisher.py", "--url", "http://aggregator:8080/publish", "--count", "5000", "--dup_ratio", "0.2", "--batch_size", "200"]
    depends_on:
      - aggregator
    container_name: publisher_service

volumes:
  data: